#!/usr/bin/env python3
# GENERATED by tools/generate_worlds.py - edit the template there, not this file.
"""Launch the 'marker_gauntlet' test world with a TurtleBot3 (default: waffle_pi).

    ros2 launch metr4202_test_worlds marker_gauntlet.launch.py
    ros2 launch metr4202_test_worlds marker_gauntlet.launch.py aruco:=false gui:=false
    ros2 launch metr4202_test_worlds marker_gauntlet.launch.py odometry:=encoder odom_error:=0.03
"""

import os
import re
import tempfile

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import (DeclareLaunchArgument, IncludeLaunchDescription, LogInfo, OpaqueFunction,
                            SetEnvironmentVariable)
from launch.conditions import IfCondition
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration, PythonExpression
from launch_ros.actions import Node

WORLD = 'marker_gauntlet'
DEFAULT_X, DEFAULT_Y, DEFAULT_YAW = '-4.25', '4.25', '0.0000'


def spawn_robot(context, sdf_path, tb3_model):
    """Spawn the TurtleBot3; with odometry:=encoder, from a copy whose /odom comes from the wheels.

    The stock model leaves gazebo_ros_diff_drive's <odometry_source> at its default (1 = WORLD), so
    /odom is the exact Gazebo pose and never drifts. Source 0 (ENCODER) integrates wheel rotation
    instead, starts at zero and accumulates error like a real robot.
    """
    actions = []
    odometry = LaunchConfiguration('odometry').perform(context).lower()
    odom_error = float(LaunchConfiguration('odom_error').perform(context))
    if odometry not in ('world', 'encoder'):
        actions.append(LogInfo(msg="odometry:=" + odometry + " is not 'world' or 'encoder'; using world"))
    if odometry == 'encoder':
        with open(sdf_path, 'r') as infp:
            sdf = infp.read()

        def miscalibrate(match):
            # The plugin believes the wheels are (1 + odom_error) times their real size and spacing.
            return match.group(1) + repr(float(match.group(2)) * (1.0 + odom_error)) + match.group(3)
        if odom_error:
            sdf = re.sub(r'(<wheel_(?:separation|diameter)>)\s*([-+.\deE]+)\s*(</wheel_(?:separation|diameter)>)',
                         miscalibrate, sdf)
        sdf = re.sub(r'\s*<odometry_source>.*?</odometry_source>', '', sdf)
        sdf, count = re.subn(r'(<plugin[^>]*libgazebo_ros_diff_drive\.so[^>]*>)',
                             r'\1\n      <odometry_source>0</odometry_source>', sdf)
        if count == 1:
            patched = os.path.join(tempfile.gettempdir(), 'metr4202_test_worlds_%s_encoder_%d.sdf'
                                   % (tb3_model, os.getuid()))
            with open(patched, 'w') as outfp:
                outfp.write(sdf)
            sdf_path = patched
            actions.append(LogInfo(msg='odometry:=encoder (odom_error %g) -> spawning %s' % (odom_error, patched)))
        else:
            actions.append(LogInfo(msg='odometry:=encoder ignored: diff drive plugin not found in ' + sdf_path))
    actions.append(Node(
        package='gazebo_ros',
        executable='spawn_entity.py',
        arguments=[
            '-entity', tb3_model,
            '-file', sdf_path,
            '-x', LaunchConfiguration('x_pose'),
            '-y', LaunchConfiguration('y_pose'),
            '-z', '0.01',
            '-Y', LaunchConfiguration('yaw'),
        ],
        output='screen',
    ))
    return actions


def generate_launch_description():
    package_dir = get_package_share_directory('metr4202_test_worlds')
    pkg_gazebo_ros = get_package_share_directory('gazebo_ros')
    pkg_tb3_gazebo = get_package_share_directory('turtlebot3_gazebo')

    # Same behaviour as the reference package, except the model defaults to waffle_pi.
    tb3_model = os.environ.get('TURTLEBOT3_MODEL', 'waffle_pi')
    sdf_path = os.path.join(pkg_tb3_gazebo, 'models', 'turtlebot3_' + tb3_model, 'model.sdf')
    urdf_path = os.path.join(pkg_tb3_gazebo, 'urdf', 'turtlebot3_' + tb3_model + '.urdf')
    with open(urdf_path, 'r') as infp:
        robot_desc = infp.read()

    use_sim_time = LaunchConfiguration('use_sim_time')
    aruco = LaunchConfiguration('aruco')

    # The ArUco materials/textures live in <share>/resource/media, exactly like
    # metr4202_aruco_explore. Gazebo's own resources must stay on the path too.
    resource_path = os.path.join(package_dir, 'resource')
    if os.environ.get('GAZEBO_RESOURCE_PATH'):
        resource_path = os.environ['GAZEBO_RESOURCE_PATH'] + os.pathsep + resource_path
    else:
        resource_path = '/usr/share/gazebo-11' + os.pathsep + resource_path

    world = PythonExpression([
        "'", os.path.join(package_dir, 'worlds', WORLD), "' + ",
        "('.world' if '", aruco, "'.lower() in ('true', '1', 'yes') else '_no_aruco.world')",
    ])

    gzserver_cmd = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(os.path.join(pkg_gazebo_ros, 'launch', 'gzserver.launch.py')),
        launch_arguments={'world': world}.items(),
    )
    gzclient_cmd = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(os.path.join(pkg_gazebo_ros, 'launch', 'gzclient.launch.py')),
        condition=IfCondition(LaunchConfiguration('gui')),
    )
    robot_state_publisher_cmd = Node(
        package='robot_state_publisher',
        executable='robot_state_publisher',
        name='robot_state_publisher',
        output='screen',
        parameters=[{'use_sim_time': use_sim_time, 'robot_description': robot_desc}],
    )
    spawn_turtlebot_cmd = OpaqueFunction(function=spawn_robot, args=[sdf_path, tb3_model])

    return LaunchDescription([
        DeclareLaunchArgument('use_sim_time', default_value='true'),
        DeclareLaunchArgument('aruco', default_value='true',
                              description='false = same maze without the ArUco columns'),
        DeclareLaunchArgument('gui', default_value='true',
                              description='false = run gzserver only (headless)'),
        DeclareLaunchArgument('x_pose', default_value=DEFAULT_X, description='spawn x [m]'),
        DeclareLaunchArgument('y_pose', default_value=DEFAULT_Y, description='spawn y [m]'),
        DeclareLaunchArgument('yaw', default_value=DEFAULT_YAW, description='spawn heading [rad]'),
        DeclareLaunchArgument('odometry', default_value='world',
                              description='world = stock model (/odom is ground truth); '
                                          'encoder = wheel odometry that starts at zero and drifts'),
        DeclareLaunchArgument('odom_error', default_value='0.0',
                              description='with odometry:=encoder: fractional wheel calibration error, '
                                          'e.g. 0.03 makes /odom over-read distance and under-read turns'),
        LogInfo(msg='GAZEBO_RESOURCE_PATH: ' + resource_path),
        LogInfo(msg='TurtleBot3 model: ' + tb3_model + ' (waffle_pi is the one with a camera)'),
        SetEnvironmentVariable(name='GAZEBO_RESOURCE_PATH', value=resource_path),
        SetEnvironmentVariable(name='TURTLEBOT3_MODEL', value=tb3_model),
        gzserver_cmd,
        gzclient_cmd,
        robot_state_publisher_cmd,
        spawn_turtlebot_cmd,
    ])
